# Generated by Django 5.1.2 on 2024-10-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B', 'Azul Estelar'), ('G', 'Cinza Espacial'), ('S', 'Prata'), ('M', 'Meia Noite'), ('R', 'Ouro Rosa')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], max_length=1, null=True)),
                ('name', models.CharField(max_length=100)),
                ('notebook_id', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=10)),
                ('emc', models.CharField(blank=True, max_length=10, null=True)),
                ('cpu', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('resolution', models.CharField(max_length=50)),
                ('screen_type', models.CharField(max_length=50)),
                ('true_tone', models.CharField(max_length=10)),
                ('screen_suport', models.CharField(max_length=100)),
                ('battery_life', models.CharField(max_length=50)),
                ('charger', models.CharField(max_length=50)),
                ('battery_connection', models.CharField(max_length=50)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('whight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('audio_type', models.CharField(max_length=200)),
                ('wifi', models.CharField(max_length=50)),
                ('bluetooth', models.CharField(max_length=50)),
                ('usb', models.CharField(max_length=50)),
                ('hdmi', models.CharField(max_length=50)),
                ('headphone_jack', models.CharField(max_length=50)),
                ('microphone', models.CharField(max_length=50)),
                ('camera_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(max_length=100)),
                ('colors', models.ManyToManyField(to='comparamac.color')),
            ],
        ),
    ]
