# Generated by Django 5.1.2 on 2024-10-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparamac', '0002_rename_color_cor_rename_name_cor_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='nanomeme',
            new_name='nome',
        ),
    ]
